### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by olifolkerd** [nealerickson/laravel-azure-blob-storage#1]
when trying to check if a container exists i get the following errors:

03] Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

The MAC signature found in the HTTP request 'SIG IS HERE' is not the same as any computed signature. Server used following string to sign.

any idea what is causing the issue?

**Comment by nealerickson** [comment]
Have you have already run the following command to copy the config file into your app directory?

`php artisan config:publish heedworks/laravel-azure-blob-storage`

You should have a config.php file in `app/config/packages/heedworks/laravel-azure-blob-storage`. In that file you will need to add your Azure account information.

Can you please double check to make sure those credentials are correct? I am able to reproduce that error by putting invalid account credentials in my config.php file.

**Comment by olifolkerd** [comment]
hi,

thanks for the fast reply. yes i can confirm those details are correct, i
have setup a test stie to try this with, these are the details i have been
given by axure:
'accountUrl' => 'https://eventengineer.blob.core.windows.net/',
'accountName' => 'eventengineer',
'accountKey' =>
'zWU3w0svmvFPDwFV1P7zDyYQD3DMhvM3zVilYtvw5SwwCPFLoGuFkWJpG+EBRL15SL4RQSvVty4RkK7x7Em4Kg=='

Cheers

Oli

**Comment by nealerickson** [comment]
Drop the trailing slash in the accountUrl and you should be fine.

**Comment by nealerickson** [comment]
No problem. Glad it is working for you.
