### ISSUE TITLE
Metadata name does not adhere to metadata naming conventions

### ISSUE THREAD

**Issue by georgezams** [nealerickson/laravel-azure-blob-storage#2]
Hi and thank you for your nice work!
I am getting an error Metadata name does not adhere to metadata naming conventions when i try to add any Metadata either to the container or blob.. 

Your help would be appreciated!

**Comment by nealerickson** [comment]
An exception is thrown with that message from the `generateMetadataHeaders` method in `lib/Beberlei/AzureBlobStorage/BlobClient.php`, when `isValidMetadataName` returns false. 

Valid metadata must be a non-empty string matching the regex `^[a-zA-Z0-9_@][a-zA-Z0-9_]*$`.
